name: pptorch

channels:
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - jupyter==1.0.0
      - ipykernel==7.3.0
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - numpy==1.23.5
      - pandas==2.3.3
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - pillow==12.3.0
      - torch==2.14.0
      - torchvision==0.29.0
      - vit-pytorch==1.26.6
      - linformer==0.2.3